################################################################################
# \file Makefile
# \brief Makefile for COMPONENT_BSXLITE (Bosch BSXlite sensor fusion + BMI270)
################################################################################

SOURCES+=source/sensor_hub_fusion.c
INCLUDES+=.
# Prebuilt Bosch BSXlite library for CM33 (GCC_ARM)
LDLIBS+=libalgobsx.a
